In [87]:
import pandas as pd
from tqdm.notebook import tqdm
import json

In [33]:
pwd

'/home/yuchen/kaggle/chaii/working/translate'

In [117]:
df = pd.read_csv('../../input/translate-cache/squad2_translated_0905.csv')
df = df[(df['answer'].notna())|(df['answer_start_char_idx']==-1)].reset_index(drop=True)
df[df.select_dtypes(include='int64').columns] = df.select_dtypes(include='int64').astype('int32')
df[df.select_dtypes(include='float64').columns] = df.select_dtypes(include='float64').astype('float32')
df

,id,context,question,answer,answer_start_char_idx,answer_end_char_idx,error_ta,context_ta,question_ta,answer_text_ta,answer_start_ta
0,0,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,269,286,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,பியோனஸ் எப்போது பிரபலமடையத் தொடங்கினார்?,1990 களின் பிற்பகுதியில்,272.0
1,1,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,207,226,answer does not occur once in the translated s...,NaN,NaN,NaN,NaN
2,2,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce leave Destiny's Child and bec...,2003,526,530,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,டெஸ்டினியின் குழந்தையை விட்டு பியோனஸ் எப்போது ...,2003,559.0
3,3,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,In what city and state did Beyonce grow up?,"Houston, Texas",166,180,answer does not occur once in the translated s...,NaN,NaN,NaN,NaN
4,4,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,In which decade did Beyonce become famous?,late 1990s,276,286,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,எந்த தசாப்தத்தில் பியோனஸ் பிரபலமானது?,1990 களின் பிற்பகுதியில்,272.0
...,...,...,...,...,...,...,...,...,...,...,...
130313,130314,"The term ""matter"" is used throughout physics i...",Physics has broadly agreed on the definition o...,NaN,-1,-1,success,"""பொருள்"" என்ற சொல் இயற்பியல் முழுவதும் திகைப்ப...",இயற்பியல் பரந்த அளவில் என்ன வரையறைக்கு ஒப்புக்...,NaN,-1.0
130314,130315,"The term ""matter"" is used throughout physics i...",Who coined the term partonic matter?,NaN,-1,-1,success,"""பொருள்"" என்ற சொல் இயற்பியல் முழுவதும் திகைப்ப...",பார்டோனிக் மேட்டர் என்ற வார்த்தையை உருவாக்கியவ...,NaN,-1.0
130315,130316,"The term ""matter"" is used throughout physics i...",What is another name for anti-matter?,NaN,-1,-1,success,"""பொருள்"" என்ற சொல் இயற்பியல் முழுவதும் திகைப்ப...",பொருளுக்கு எதிரான மற்றொரு பெயர் என்ன?,NaN,-1.0
130316,130317,"The term ""matter"" is used throughout physics i...",Matter usually does not need to be used in con...,NaN,-1,-1,success,"""பொருள்"" என்ற சொல் இயற்பியல் முழுவதும் திகைப்ப...",பொருள் பொதுவாக எதனுடன் இணைந்து பயன்படுத்தத் தே...,NaN,-1.0
130317,130318,"The term ""matter"" is used throughout physics i...",What field of study has a variety of unusual c...,NaN,-1,-1,success,"""பொருள்"" என்ற சொல் இயற்பியல் முழுவதும் திகைப்ப...",எந்தவிதமான ஆய்வுத் துறையில் பல்வேறு அசாதாரண சூ...,NaN,-1.0

In [118]:
df2check = df[df['answer_start_ta'].notnull()]
df2check = df2check[df2check['answer_start_ta']!=-1].reset_index(drop=True)
df2check

,id,context,question,answer,answer_start_char_idx,answer_end_char_idx,error_ta,context_ta,question_ta,answer_text_ta,answer_start_ta
0,0,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,269,286,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,பியோனஸ் எப்போது பிரபலமடையத் தொடங்கினார்?,1990 களின் பிற்பகுதியில்,272.0
1,2,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce leave Destiny's Child and bec...,2003,526,530,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,டெஸ்டினியின் குழந்தையை விட்டு பியோனஸ் எப்போது ...,2003,559.0
2,4,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,In which decade did Beyonce become famous?,late 1990s,276,286,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,எந்த தசாப்தத்தில் பியோனஸ் பிரபலமானது?,1990 களின் பிற்பகுதியில்,272.0
3,8,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyoncé rise to fame?,late 1990s,276,286,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,பியோனஸ் எப்போது புகழ் பெற்றார்?,1990 களின் பிற்பகுதியில்,272.0
4,11,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyoncé release Dangerously in Love?,2003,526,530,success,பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒns...,பியான்ஸ் எப்போது காதலில் ஆபத்தானதை வெளியிட்டார்?,2003,559.0
...,...,...,...,...,...,...,...,...,...,...,...
38418,130046,"Kathmandu Metropolitan City (KMC), in order to...",In what US state did Kathmandu first establish...,Oregon,229,235,success,"காத்மாண்டு பெருநகர நகரம் (KMC), சர்வதேச உறவுகள...",எந்த அமெரிக்க மாநிலத்தில் காத்மாண்டு முதலில் ச...,ஒரேகான்,177.0
38419,130047,"Kathmandu Metropolitan City (KMC), in order to...",What was Yangon previously known as?,Rangoon,414,421,success,"காத்மாண்டு பெருநகர நகரம் (KMC), சர்வதேச உறவுகள...",யாங்கோன் முன்பு என்ன அழைக்கப்பட்டது?,ரங்கூன்,306.0
38420,130048,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,Minsk,476,481,success,"காத்மாண்டு பெருநகர நகரம் (KMC), சர்வதேச உறவுகள...",காத்மாண்டு எந்த பெலாரஷ்ய நகரத்துடன் உறவு வைத்த...,மின்ஸ்க்,356.0
38421,130049,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,1975,199,203,success,"காத்மாண்டு பெருநகர நகரம் (KMC), சர்வதேச உறவுகள...",காத்மாண்டு அதன் ஆரம்ப சர்வதேச உறவை எந்த ஆண்டில...,1975,146.0
38422,130050,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,0,27,success,"காத்மாண்டு பெருநகர நகரம் (KMC), சர்வதேச உறவுகள...",KMC இன் ஆரம்பநிலை என்றால் என்ன?,காத்மாண்டு பெருநகர நகரம்,0.0

In [119]:
# sanity check
for i in range(len(df2check)):
    context = df2check.loc[i, 'context_ta']
    answer = df2check.loc[i, 'answer_text_ta']
    start = int(df2check.loc[i, 'answer_start_ta'])
    assert context[start: start+len(answer)]==answer

In [121]:
data = {'id': [], 'context': [], 'question': [], 'answers': []}
for i in tqdm(range(len(df))):
    data['id'].append(i)
    status = df.loc[i, 'error_ta']
    if status == 'success':
        data['context'].append(df.loc[i, 'context_ta'])
        data['question'].append(df.loc[i, 'question_ta'])
        answer_text_ta = df.loc[i, 'answer_text_ta']
        if pd.isnull(answer_text_ta):
            data['answers'].append({'text': [], 'answer_start': []})
        else:
            answer_start_ta = int(df.loc[i, 'answer_start_ta'])
            assert answer_start_ta != -1 and not pd.isnull(answer_start_ta)
            data['answers'].append({'text': [answer_text_ta], 'answer_start': [int(answer_start_ta)]})
    else:
        data['context'].append(df.loc[i, 'context'])
        data['question'].append(df.loc[i, 'question'])
        data['answers'].append({'text': [df.loc[i, 'answer']], 'answer_start': [int(df.loc[i, 'answer_start_char_idx'])]})

  0%|          | 0/130318 [00:00<?, ?it/s]

In [122]:
for k, v in data.items():
    print(k, len(v))
    print(v[:5])

id 130318
[0, 1, 2, 3, 4]
context 130318
['பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒnseɪ/ bee-YON-say) (பிறப்பு செப்டம்பர் 4, 1981) ஒரு அமெரிக்க பாடகர், பாடலாசிரியர், பதிவு தயாரிப்பாளர் மற்றும் நடிகை. டெக்சாஸின் ஹூஸ்டனில் பிறந்து வளர்ந்த அவர், குழந்தையாக பல்வேறு பாட்டு மற்றும் நடன போட்டிகளில் நடித்தார், மேலும் 1990 களின் பிற்பகுதியில் ஆர் & பி பெண்-குழு டெஸ்டினிஸ் சைல்ட்டின் முன்னணி பாடகியாக புகழ் பெற்றார். அவரது தந்தை, மேத்யூ நோல்ஸால் நிர்வகிக்கப்பட்டது, இந்த குழு உலகில் அதிகம் விற்பனையாகும் பெண் குழுக்களில் ஒன்றாக மாறியது. அவர்களின் இடைவெளியில் பியோன்ஸின் முதல் ஆல்பமான டேஞ்சர்லிஸ் இன் லவ் (2003) வெளியிடப்பட்டது, இது உலகளாவிய ஒரு தனி கலைஞராக நிறுவப்பட்டது, ஐந்து கிராமி விருதுகளைப் பெற்றது மற்றும் பில்போர்டு ஹாட் 100 நம்பர் ஒன் சிங்கிள்ஸ் "கிரேஸி இன் லவ்" மற்றும் "பேபி பாய்" .', 'Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ bee-YON-say) (born September 4, 1981) is an American singer, songwriter, record producer and actress. Born and raised in Houston, Texas, she performed in various singing and dancing competitions as a child, and rose to fame in the late 1990s as lead singer of R&B girl-group Destiny\'s Child. Managed by her father, Mathew Knowles, the group became one of the world\'s best-selling girl groups of all time. Their hiatus saw the release of Beyoncé\'s debut album, Dangerously in Love (2003), which established her as a solo artist worldwide, earned five Grammy Awards and featured the Billboard Hot 100 number-one singles "Crazy in Love" and "Baby Boy".', 'பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒnseɪ/ bee-YON-say) (பிறப்பு செப்டம்பர் 4, 1981) ஒரு அமெரிக்க பாடகர், பாடலாசிரியர், பதிவு தயாரிப்பாளர் மற்றும் நடிகை. டெக்சாஸின் ஹூஸ்டனில் பிறந்து வளர்ந்த அவர், குழந்தையாக பல்வேறு பாட்டு மற்றும் நடன போட்டிகளில் நடித்தார், மேலும் 1990 களின் பிற்பகுதியில் ஆர் & பி பெண்-குழு டெஸ்டினிஸ் சைல்ட்டின் முன்னணி பாடகியாக புகழ் பெற்றார். அவரது தந்தை, மேத்யூ நோல்ஸால் நிர்வகிக்கப்பட்டது, இந்த குழு உலகில் அதிகம் விற்பனையாகும் பெண் குழுக்களில் ஒன்றாக மாறியது. அவர்களின் இடைவெளியில் பியோன்ஸின் முதல் ஆல்பமான டேஞ்சர்லிஸ் இன் லவ் (2003) வெளியிடப்பட்டது, இது உலகளாவிய ஒரு தனி கலைஞராக நிறுவப்பட்டது, ஐந்து கிராமி விருதுகளைப் பெற்றது மற்றும் பில்போர்டு ஹாட் 100 நம்பர் ஒன் சிங்கிள்ஸ் "கிரேஸி இன் லவ்" மற்றும் "பேபி பாய்" .', 'Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ bee-YON-say) (born September 4, 1981) is an American singer, songwriter, record producer and actress. Born and raised in Houston, Texas, she performed in various singing and dancing competitions as a child, and rose to fame in the late 1990s as lead singer of R&B girl-group Destiny\'s Child. Managed by her father, Mathew Knowles, the group became one of the world\'s best-selling girl groups of all time. Their hiatus saw the release of Beyoncé\'s debut album, Dangerously in Love (2003), which established her as a solo artist worldwide, earned five Grammy Awards and featured the Billboard Hot 100 number-one singles "Crazy in Love" and "Baby Boy".', 'பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒnseɪ/ bee-YON-say) (பிறப்பு செப்டம்பர் 4, 1981) ஒரு அமெரிக்க பாடகர், பாடலாசிரியர், பதிவு தயாரிப்பாளர் மற்றும் நடிகை. டெக்சாஸின் ஹூஸ்டனில் பிறந்து வளர்ந்த அவர், குழந்தையாக பல்வேறு பாட்டு மற்றும் நடன போட்டிகளில் நடித்தார், மேலும் 1990 களின் பிற்பகுதியில் ஆர் & பி பெண்-குழு டெஸ்டினிஸ் சைல்ட்டின் முன்னணி பாடகியாக புகழ் பெற்றார். அவரது தந்தை, மேத்யூ நோல்ஸால் நிர்வகிக்கப்பட்டது, இந்த குழு உலகில் அதிகம் விற்பனையாகும் பெண் குழுக்களில் ஒன்றாக மாறியது. அவர்களின் இடைவெளியில் பியோன்ஸின் முதல் ஆல்பமான டேஞ்சர்லிஸ் இன் லவ் (2003) வெளியிடப்பட்டது, இது உலகளாவிய ஒரு தனி கலைஞராக நிறுவப்பட்டது, ஐந்து கிராமி விருதுகளைப் பெற்றது மற்றும் பில்போர்டு ஹாட் 100 நம்பர் ஒன் சிங்கிள்ஸ் "கிரேஸி இன் லவ்" மற்றும் "பேபி பாய்" .']
question 130318
['பியோனஸ் எப்போது பிரபலமடையத் தொடங்கினார்?', 'What areas did Beyonce compete in when she was growing up?', 'டெஸ்டினியின் குழந்தையை விட்டு பியோனஸ் எப்போது தனி பாடகராக ஆனார்?', 'In what city and state did Beyonce  grow up? ', 'எந்த தசாப்தத்தில் பியோனஸ் பிரபலமானது?']
answers 130318
[{'text': ['1990 களின் பிற்பகுதியில்'], 'answer_start': [272]}, {'text': ['singing and dancing'], 'answer_start': [207]}, {'text': ['2003'], 'answer_start': [559]}, {'text': ['Houston, Texas'], 'answer_start': [166]}, {'text': ['1990 களின் பிற்பகுதியில்'], 'answer_start': [272]}]

In [123]:
# last sanity check
for i in tqdm(range(len(data['id']))):
    if len(data['answers'][i]['text']) == 0: continue
    context = data['context'][i]
    question = data['question'][i]
    answer_text = data['answers'][i]['text'][0]
    answer_start = data['answers'][i]['answer_start'][0]
    assert context[answer_start:answer_start+len(answer_text)]==answer_text

  0%|          | 0/130318 [00:00<?, ?it/s]

In [125]:
with open('squad2_enta.json', 'w') as f:
    json.dump(data, f, indent=4)

In [126]:
with open('squad2_enta.json', 'r') as f:
    data = json.load(f)
for k, v in data.items():
    print(k, len(v))
    print(v[:5])

id 130318
[0, 1, 2, 3, 4]
context 130318
['பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒnseɪ/ bee-YON-say) (பிறப்பு செப்டம்பர் 4, 1981) ஒரு அமெரிக்க பாடகர், பாடலாசிரியர், பதிவு தயாரிப்பாளர் மற்றும் நடிகை. டெக்சாஸின் ஹூஸ்டனில் பிறந்து வளர்ந்த அவர், குழந்தையாக பல்வேறு பாட்டு மற்றும் நடன போட்டிகளில் நடித்தார், மேலும் 1990 களின் பிற்பகுதியில் ஆர் & பி பெண்-குழு டெஸ்டினிஸ் சைல்ட்டின் முன்னணி பாடகியாக புகழ் பெற்றார். அவரது தந்தை, மேத்யூ நோல்ஸால் நிர்வகிக்கப்பட்டது, இந்த குழு உலகில் அதிகம் விற்பனையாகும் பெண் குழுக்களில் ஒன்றாக மாறியது. அவர்களின் இடைவெளியில் பியோன்ஸின் முதல் ஆல்பமான டேஞ்சர்லிஸ் இன் லவ் (2003) வெளியிடப்பட்டது, இது உலகளாவிய ஒரு தனி கலைஞராக நிறுவப்பட்டது, ஐந்து கிராமி விருதுகளைப் பெற்றது மற்றும் பில்போர்டு ஹாட் 100 நம்பர் ஒன் சிங்கிள்ஸ் "கிரேஸி இன் லவ்" மற்றும் "பேபி பாய்" .', 'Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ bee-YON-say) (born September 4, 1981) is an American singer, songwriter, record producer and actress. Born and raised in Houston, Texas, she performed in various singing and dancing competitions as a child, and rose to fame in the late 1990s as lead singer of R&B girl-group Destiny\'s Child. Managed by her father, Mathew Knowles, the group became one of the world\'s best-selling girl groups of all time. Their hiatus saw the release of Beyoncé\'s debut album, Dangerously in Love (2003), which established her as a solo artist worldwide, earned five Grammy Awards and featured the Billboard Hot 100 number-one singles "Crazy in Love" and "Baby Boy".', 'பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒnseɪ/ bee-YON-say) (பிறப்பு செப்டம்பர் 4, 1981) ஒரு அமெரிக்க பாடகர், பாடலாசிரியர், பதிவு தயாரிப்பாளர் மற்றும் நடிகை. டெக்சாஸின் ஹூஸ்டனில் பிறந்து வளர்ந்த அவர், குழந்தையாக பல்வேறு பாட்டு மற்றும் நடன போட்டிகளில் நடித்தார், மேலும் 1990 களின் பிற்பகுதியில் ஆர் & பி பெண்-குழு டெஸ்டினிஸ் சைல்ட்டின் முன்னணி பாடகியாக புகழ் பெற்றார். அவரது தந்தை, மேத்யூ நோல்ஸால் நிர்வகிக்கப்பட்டது, இந்த குழு உலகில் அதிகம் விற்பனையாகும் பெண் குழுக்களில் ஒன்றாக மாறியது. அவர்களின் இடைவெளியில் பியோன்ஸின் முதல் ஆல்பமான டேஞ்சர்லிஸ் இன் லவ் (2003) வெளியிடப்பட்டது, இது உலகளாவிய ஒரு தனி கலைஞராக நிறுவப்பட்டது, ஐந்து கிராமி விருதுகளைப் பெற்றது மற்றும் பில்போர்டு ஹாட் 100 நம்பர் ஒன் சிங்கிள்ஸ் "கிரேஸி இன் லவ்" மற்றும் "பேபி பாய்" .', 'Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ bee-YON-say) (born September 4, 1981) is an American singer, songwriter, record producer and actress. Born and raised in Houston, Texas, she performed in various singing and dancing competitions as a child, and rose to fame in the late 1990s as lead singer of R&B girl-group Destiny\'s Child. Managed by her father, Mathew Knowles, the group became one of the world\'s best-selling girl groups of all time. Their hiatus saw the release of Beyoncé\'s debut album, Dangerously in Love (2003), which established her as a solo artist worldwide, earned five Grammy Awards and featured the Billboard Hot 100 number-one singles "Crazy in Love" and "Baby Boy".', 'பியான்ஸ் கிசெல்லே நோல்ஸ்-கார்ட்டர் (/ biːˈjɒnseɪ/ bee-YON-say) (பிறப்பு செப்டம்பர் 4, 1981) ஒரு அமெரிக்க பாடகர், பாடலாசிரியர், பதிவு தயாரிப்பாளர் மற்றும் நடிகை. டெக்சாஸின் ஹூஸ்டனில் பிறந்து வளர்ந்த அவர், குழந்தையாக பல்வேறு பாட்டு மற்றும் நடன போட்டிகளில் நடித்தார், மேலும் 1990 களின் பிற்பகுதியில் ஆர் & பி பெண்-குழு டெஸ்டினிஸ் சைல்ட்டின் முன்னணி பாடகியாக புகழ் பெற்றார். அவரது தந்தை, மேத்யூ நோல்ஸால் நிர்வகிக்கப்பட்டது, இந்த குழு உலகில் அதிகம் விற்பனையாகும் பெண் குழுக்களில் ஒன்றாக மாறியது. அவர்களின் இடைவெளியில் பியோன்ஸின் முதல் ஆல்பமான டேஞ்சர்லிஸ் இன் லவ் (2003) வெளியிடப்பட்டது, இது உலகளாவிய ஒரு தனி கலைஞராக நிறுவப்பட்டது, ஐந்து கிராமி விருதுகளைப் பெற்றது மற்றும் பில்போர்டு ஹாட் 100 நம்பர் ஒன் சிங்கிள்ஸ் "கிரேஸி இன் லவ்" மற்றும் "பேபி பாய்" .']
question 130318
['பியோனஸ் எப்போது பிரபலமடையத் தொடங்கினார்?', 'What areas did Beyonce compete in when she was growing up?', 'டெஸ்டினியின் குழந்தையை விட்டு பியோனஸ் எப்போது தனி பாடகராக ஆனார்?', 'In what city and state did Beyonce  grow up? ', 'எந்த தசாப்தத்தில் பியோனஸ் பிரபலமானது?']
answers 130318
[{'text': ['1990 களின் பிற்பகுதியில்'], 'answer_start': [272]}, {'text': ['singing and dancing'], 'answer_start': [207]}, {'text': ['2003'], 'answer_start': [559]}, {'text': ['Houston, Texas'], 'answer_start': [166]}, {'text': ['1990 களின் பிற்பகுதியில்'], 'answer_start': [272]}]

In [132]:
from sklearn.model_selection import train_test_split
df['if_success'] = df['error_ta']=='success'
df_train, df_valid = train_test_split(df, test_size=0.2, random_state=42, stratify=df['if_success'])
df_train = df_train.reset_index(drop=True)
df_valid = df_valid.reset_index(drop=True)
df_train

,id,context,question,answer,answer_start_char_idx,answer_end_char_idx,error_ta,context_ta,question_ta,answer_text_ta,answer_start_ta,if_success
0,97874,"Miami is a major television production center,...",What is the name of the business that produces...,NaN,-1,-1,success,"மியாமி ஒரு பெரிய தொலைக்காட்சி தயாரிப்பு மையம்,...",டெலிமுண்டோவின் அசல் நிரலாக்கத்தின் ஒரு சிறிய ப...,NaN,-1.0,True
1,44587,In response to the criticism of the Kinsey sca...,What does KSOG stand for?,Klein sexual orientation grid,128,157,answer does not occur once in the translated s...,NaN,NaN,NaN,NaN,False
2,56917,The Russian army withdrew and retreated past M...,Approximately how many French men and horses f...,"10,000",471,477,success,ரஷ்ய இராணுவம் மாஸ்கோவைக் கடந்து பின்வாங்கியது....,நவம்பர் 8/9 இரவில் தோராயமாக எத்தனை பிரெஞ்சு ஆண...,"10,000",578.0,True
3,90082,"Instead, he formulated the spearhead model of ...",What does Popper think is more likely to be le...,NaN,-1,-1,success,"அதற்கு பதிலாக, அவர் மரபணு பன்மைத்துவத்தின் ஒரு...",பினோடைப்பின் மாற்றங்களை விட ஒரு உயிரினத்திற்கு...,NaN,-1.0,True
4,29492,The city hosted the 1964 Democratic National C...,Who was the Governor of New Jersey in 1964?,Richard J. Hughes,380,397,answer does not occur once in the translated s...,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...
104249,65831,Norfolk Island is the only non-mainland Austra...,"During 1979-2015, Legislative Assembly terms l...",three years,499,510,answer does not occur once in the translated s...,NaN,NaN,NaN,NaN,False
104250,68665,This view of 'diplomatic drift' as the cause o...,What did A.W Kinglake make the British out to be?,as victims,123,133,answer does not occur once in the translated s...,NaN,NaN,NaN,NaN,False
104251,11461,"In 1969, Schwarzenegger met Barbara Outland (l...",What did Baker say Schwarzenegger didn't under...,polite society,1509,1523,answer does not occur once in the translated s...,NaN,NaN,NaN,NaN,False
104252,29677,Clinical immunology is the study of diseases c...,The study of diseases caused by immune system ...,Clinical immunology,0,19,success,மருத்துவ நோயெதிர்ப்பு என்பது நோயெதிர்ப்பு மண்ட...,நோயெதிர்ப்பு மண்டலக் கோளாறுகளால் ஏற்படும் நோய்...,மருத்துவ நோயெதிர்ப்பு,0.0,True
104253,81493,The effects of local surface low pressure are ...,Where is the Sahara located?,NaN,-1,-1,success,உள்ளூர் மேற்பரப்பு குறைந்த அழுத்தத்தின் விளைவு...,சஹாரா எங்கே அமைந்துள்ளது?,NaN,-1.0,True

In [134]:
def to_dict(df):
    data = {'id': [], 'context': [], 'question': [], 'answers': []}
    for i in tqdm(range(len(df))):
        data['id'].append(i)
        status = df.loc[i, 'error_ta']
        if status == 'success':
            data['context'].append(df.loc[i, 'context_ta'])
            data['question'].append(df.loc[i, 'question_ta'])
            answer_text_ta = df.loc[i, 'answer_text_ta']
            if pd.isnull(answer_text_ta):
                data['answers'].append({'text': [], 'answer_start': []})
            else:
                answer_start_ta = int(df.loc[i, 'answer_start_ta'])
                assert answer_start_ta != -1 and not pd.isnull(answer_start_ta)
                data['answers'].append({'text': [answer_text_ta], 'answer_start': [int(answer_start_ta)]})
        else:
            data['context'].append(df.loc[i, 'context'])
            data['question'].append(df.loc[i, 'question'])
            data['answers'].append({'text': [df.loc[i, 'answer']], 'answer_start': [int(df.loc[i, 'answer_start_char_idx'])]})
    return data
train = to_dict(df_train)
valid = to_dict(df_valid)

  0%|          | 0/104254 [00:00<?, ?it/s]

  0%|          | 0/26064 [00:00<?, ?it/s]

In [137]:
with open('squad2_enta_train.json', 'w') as f:
    json.dump(train, f, indent=4)
with open('squad2_enta_valid.json', 'w') as f:
    json.dump(valid, f, indent=4)